<a href="https://colab.research.google.com/github/madan-genai/machine-learning/blob/main/Fake_news_classification_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("/content/FA-KES-Dataset.csv", encoding='latin1')

In [6]:
df.head()

,unit_id,article_title,article_content,source,date,location,labels
0,1914947530,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,nna,4/5/2017,idlib,0
1,1914947532,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,nna,4/7/2017,homs,0
2,1914947533,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,nna,4/16/2017,aleppo,0
3,1914947534,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,nna,4/19/2017,aleppo,0
4,1914947535,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,nna,7/10/2016,aleppo,0

In [7]:
df.isnull().sum()

unit_id            0
article_title      0
article_content    0
source             0
date               0
location           0
labels             0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804 entries, 0 to 803
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   unit_id          804 non-null    int64
 1   article_title    804 non-null    object
 2   article_content  804 non-null    object
 3   source           804 non-null    object
 4   date             804 non-null    object
 5   location         804 non-null    object
 6   labels           804 non-null    int64
dtypes: int64(2), object(5)
memory usage: 44.1+ KB

In [9]:
df.dropna()

,unit_id,article_title,article_content,source,date,location,labels
0,1914947530,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,nna,4/5/2017,idlib,0
1,1914947532,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,nna,4/7/2017,homs,0
2,1914947533,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,nna,4/16/2017,aleppo,0
3,1914947534,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,nna,4/19/2017,aleppo,0
4,1914947535,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,nna,7/10/2016,aleppo,0
...,...,...,...,...,...,...,...
799,1965511221,Turkish Bombardment Kills 20 Civilians in Syria,28-08-2016 Turkish Bombardment Kills 20 Civili...,manar,8/28/2016,aleppo,1
800,1965511222,Martyrs as Terrorists Shell Aleppos Salah Eddin,17-08-2016 Martyrs as Terrorists Shell Aleppos...,manar,8/1/2016,aleppo,1
801,1965511224,Chemical Attack Kills Five Syrians in Aleppo SANA,03-08-2016 Chemical Attack Kills Five Syrians ...,manar,8/3/2016,aleppo,0
802,1965511226,5 Killed as Russian Military Chopper Shot down...,01-08-2016 5 Killed as Russian Military Choppe...,manar,8/1/2016,idlib,1
803,1965511231,Syrian Army Kills 48 ISIL Terrorists in Deir E...,April 6 2017 Syrian Army Kills 48 ISIL Terrori...,manar,4/4/2017,deir ezzor,1

In [10]:
df.head()

,unit_id,article_title,article_content,source,date,location,labels
0,1914947530,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,nna,4/5/2017,idlib,0
1,1914947532,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,nna,4/7/2017,homs,0
2,1914947533,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,nna,4/16/2017,aleppo,0
3,1914947534,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,nna,4/19/2017,aleppo,0
4,1914947535,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,nna,7/10/2016,aleppo,0

In [11]:
X=df.drop('labels',axis=1)

In [12]:
Y=df["labels"]

In [13]:
X.shape

(804, 6)

In [14]:
Y.shape

(804,)

In [15]:
!pip install tensorflow
import tensorflow as tf

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [17]:
voc_size=5000

# ONE HOT REPRESTATION

In [18]:
messages=X.copy()

In [21]:
messages["article_title"][1]

'Homs governor says U.S. attack caused deaths but doesnt see big human losses'

In [22]:
messages

,unit_id,article_title,article_content,source,date,location
0,1914947530,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,nna,4/5/2017,idlib
1,1914947532,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,nna,4/7/2017,homs
2,1914947533,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,nna,4/16/2017,aleppo
3,1914947534,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,nna,4/19/2017,aleppo
4,1914947535,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,nna,7/10/2016,aleppo
...,...,...,...,...,...,...
799,1965511221,Turkish Bombardment Kills 20 Civilians in Syria,28-08-2016 Turkish Bombardment Kills 20 Civili...,manar,8/28/2016,aleppo
800,1965511222,Martyrs as Terrorists Shell Aleppos Salah Eddin,17-08-2016 Martyrs as Terrorists Shell Aleppos...,manar,8/1/2016,aleppo
801,1965511224,Chemical Attack Kills Five Syrians in Aleppo SANA,03-08-2016 Chemical Attack Kills Five Syrians ...,manar,8/3/2016,aleppo
802,1965511226,5 Killed as Russian Military Chopper Shot down...,01-08-2016 5 Killed as Russian Military Choppe...,manar,8/1/2016,idlib
803,1965511231,Syrian Army Kills 48 ISIL Terrorists in Deir E...,April 6 2017 Syrian Army Kills 48 ISIL Terrori...,manar,4/4/2017,deir ezzor

In [23]:
import nltk
import re
from nltk.corpus import stopwords

In [24]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [27]:
## data preprocessing
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['article_title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words("english")]
  review = " ".join(review)
  corpus.append(review)

In [28]:
corpus

['syria attack symptom consist nerv agent use',
 'hom governor say u attack caus death doesnt see big human loss',
 'death toll aleppo bomb attack least',
 'aleppo bomb blast kill six syrian state tv',
 'syria rebel dead fight key aleppo road',
 'suicid bomb kill least northeast syria',
 'dead heavi u raid syria stronghold',
 'suicid bomber kill assad clan hometown',
 'explos rock town damascu',
 'damascu explos due rocket bomb',
 'syrian regim step aerial assault douma',
 'hizballah lead regim offens southern syria',
 'syrian opposit remain divid',
 'video show murder syrian activist',
 'syria nusra front stage deadli suicid bomb aleppo',
 'regim troop thwart rebel attack syria aleppo',
 'ahrar al sham leader kill syria',
 'barrel bomb kill town syria',
 'rebel advanc north western syria',
 'isra strike syrian town kill pro regim fighter',
 'syria armi plane crash rebel held town',
 'syrian regim reveng attack kill score qalamoun',
 'chemic massacr idlib defi world',
 'bu bomb mark end tragic evacu deal syria',
 'six kill aleppo bomb evacu syrian town resum',
 'kill suspect ga attack syria idlib',
 'msf syrian regim use chemic weapon hama',
 'toxic ga drop syrian town russian helicopt shot',
 'syrian opposit spark aleppo front reliev north fraction',
 'dozen kill intern coalit airstrik manbij',
 'thirti kill syrian strike damascan suburb town',
 'russian syrian regim use intern ban bomb attack aleppo',
 'syria kurdish islamist violenc kill al qaeda link fighter',
 'syrian armi advanc near aleppo',
 'monitor peopl execut forc loyal regim children',
 'suicid bomber kill assad clan hometown',
 'us led airstrik target isi stronghold raqqa',
 'assad regim launch oper latakia region attack syrian turkmen villag',
 'assad regim kill civilian aleppo monitor',
 'russian airstrik hit syrian opposit forc',
 'syrian warplan crash market northwest town ariha near turkish border kill wound dozen',
 'suicid bomb attack syria idlib mosqu kill senior nusra front leader',
 'civilian kill syria hasakeh motorbik bomber attack',
 'medic among least dead regim shell opposit held syrian town',
 'assad regim airstrik kill civilian syria aleppo',
 'coalit airstrik kill civilian daesh held villag syria manbij',
 'assad regim surround aleppo opposit group resist despit intens raid',
 'us jet kill least civilian syria',
 'fatal expect increas suicid blast syria',
 'us led air strike syria kill dozen civilian',
 'syrian opposit advanc key aleppo district',
 'two russian pilot kill syria daesh down chopper',
 'least dead bomb hit refuge camp syria idlib',
 'ga attack hit rebel held area aleppo report',
 'syrian regim forc drop vacuum bomb idlib',
 'chemic attack idlib draw intern condemn',
 'regim air strike kill syria rebel held region',
 'air strike kill least northwestern syria',
 'multipl daesh suicid bomber attack refuge camp syria',
 'air strike syria kill eight white helmet activist',
 'air strike hit hospit kill peopl idlib',
 'deadli bomb blast hit syria aleppo',
 'least kill bomb hit bu convoy syria',
 'suicid bomber kill syria hasakah',
 'bomb continu fall syria despit regim truce',
 'syrian rebel fighter kill suicid bomb attack',
 'score syrian rebel kill key aleppo road',
 'us led coalit raid kill score civilian syria',
 'dozen kill bombard rebel held aleppo',
 'seven children kill syria rebel held aleppo',
 'syria airstrik destroy idlib msf hospit leav dead',
 'dozen kill russian air raid held raqqa',
 'four kill suspect ga attack aleppo',
 'three women kill attend funer syria madaya',
 'violenc rage syria dozen kill',
 'civilian kill syria aleppo',
 'syrian regim bomb kurdish fighter second day',
 'barrel bomb attack kill children syria aleppo',
 'children kill syria hom napalm mortar round',
 'kill regim strike besieg hom neighbourhood',
 'dozen kill hospit damag strike hit northwest syria',
 'score kill ga attack rebel held syria town',
 'syrian regim airstrik kill civilian near damascu',
 'shell rebel bastion near syrian capit kill',
 'syrian airbas struck us missil what damag',
 'strike syria idlib kill includ five children',
 'sarin nerv ga use syria british scientist',
 'syria rebel battl break aleppo sieg',
 'syrian children kill west aleppo school attack',
 'idlib bomb deadliest school attack syria war',
 'student among score dead raid hit syria school',
 'two dead twenti injur syrian regim chlorin attack',
 'heavi syrian regim bomb idlib kill civilian',
 'russia say belgian strike kill six aleppo region',
 'hour bombard aleppo kill',
 'dozen kill car bomb attack syrian rebel',
 'airstrik continu rain east aleppo',
 'russia launch new crippl air raid aleppo',
 'eleven kill syrian regim control area aleppo',
 'air raid kill syrian held villag',
 'suicid attack syria wed kill',
 'suicid attack kurdish wed syria kill',
 'two kill qatar red crescent syria clinic bomb',
 'syrian refuge camp hit missil bomb',
 'aleppo score kill airstrik target un aid convoy',
 'first civilian kill aleppo sinc start ceasefir',
 'syrian children kill missil attack school',
 'five dead syria airstrik ahead plan ceasefir',
 'syria regim kill civilian hama airstrik',
 'hundr dead fresh airstrik hit syria aleppo',
 'deadli aleppo convoy attack threaten aid distribut syria',
 'four medic kill strike clinic near aleppo',
 'syrian civil defenc us russia regim attack aid convoy',
 'syrian regim repel rebel offens near aleppo kill',
 'syrian regim offens northern aleppo leav dead',
 'unicef confirm children among deir ez zor dead',
 'score civilian kill airstrik raqqa',
 'heavi regim loss islam state raqqa counteroffens',
 'three children kill regim airstrik hom',
 'four hizballah member kill fight syria',
 'dozen dead suspect russian strike idlib marketplac',
 'airstrik syria kill dozen start ramadan',
 'dozen syrian regim air raid rebel held aleppo',
 'syrian regim airstrik kill dozen around aleppo',
 'airstrik kill civilian syria safe zone monitor',
 'us led strike kill civilian syria raqqa',
 'deadli twin bomb hit damascu polic station',
 'russian airstrik kill score flee civilian deir az zor',
 'syrian regim airstrik idlib market kill children',
 'tripl suicid attack near damascu polic hq ministri',
 'rebel shell kill four civilian damascu monitor',
 'three white helmet worker six children kill syria air',
 'civilian kill relentless regim bomb besieg damascu',
 'syrian regim airstrik target besieg eastern ghouta deir az zor',
 'russian strike kill civilian syria deir az zour',
 'dead strike rebel held hospit syria',
 'aleppo bomb blast kill six syrian state',
 'dozen children dead syria evacue bomb',
 'death toll aleppo bu convoy bomb attack least observatori',
 'bomb syrian bu convoy kill wound dozen outsid aleppo',
 'death toll bomb attack syria evacue hit monitor',
 'dead clash islamist milit near damascu monitor',
 'us back syrian fighter press gunmen north',
 'strike kill includ children syria idlib monitor',
 'one dead raid syria chemic attack town monitor',
 'dead suspect syria chemic attack new toll',
 'shell rebel bastion near syria capit kill monitor',
 'suspect ga attack syria rebel held idlib kill least observatori',
 'barrel bomb attack kill children syria aleppo monitor',
 'syria regim pound kurdish posit second day',
 'syrian rebel kill group suicid blast',
 'warplan pound syria idlib battl rage aleppo',
 'rebel fire syria aleppo kill state media',
 'air raid kill near syria hospit monitor',
 'barrel bomb kill least civilian syria aleppo monitor',
 'civilian dead air strike syria rebel town monitor',
 'syria regim bomb kill rebel held aleppo monitor',
 'doubl bomb attack kill syrian kurdish citi state tv',
 'syrian state tv say kill car bomb northern syria',
 'aleppo rebel tunnel blast kill regim forc monitor',
 'us led strike kill civilian syria monitor',
 'coalit raid kill civilian stronghold syria monitor',
 'air raid kill civilian syria aleppo monitor',
 'air raid kill civilian east syria monitor',
 'air strike kill rebel held area syria aleppo monitor',
 'air strike kill includ children syria idlib monitor',
 'coalit air strike turkish armi kill group milit report',
 'rocket attack kill least syria aleppo',
 'motorbik bomber kill outsid bakeri syria hasakeh',
 'kill syria armi shell rebel town monitor',
 'medic among dead syria armi repris slain pilot',
 'syria air raid kill civilian monitor',
 'dead attack kurd held syria town monitor',
 'syria rebel rocket kill five children',
 'turkish air strike kill fighter syria monitor',
 'civilian dead syrian raid held villag monitor',
 'missil kill civilian syria aleppo monitor',
 'barrel bomb kill civilian town syria',
 'civilian kill regim air raid northern syria',
 'huge regim bomb kill held syria town monitor',
 'bomb rocket kill civilian syria aleppo monitor',
 'dead new islamist allianc attack syria aleppo monitor',
 'air strike syria kill least islam state fighter monitor',
 'syria regim air strike kill near damascu monitor',
 'syrian air strike kill peopl rebel rocket attack monitor',
 'syria strike kill rebel fire damascu monitor',
 'syria air strike kill monitor',
 'seven dead wound central damascu blast monitor',
 'syria fight kill islam state fighter monitor',
 'suicid bomber kill assad clan hometown',
 'syria forc execut children alleg rebel monitor',
 'jihadist kill clash syria kurd monitor',
 'suicid bomber kill six syria restaur report',
 'dead al qaeda attack syria kurd town',
 'dead air raid syria latakia provinc ngo',
 'syrian armi kill rebel east damascu monitor group',
 'bomb kill damascu suburb state tv',
 'least kill syrian weapon depot blast',
 'syria regim raid kill camp displac ngo',
 'attack syria oil field kill monitor',
 'syria air strike kill children women aleppo monitor',
 'syrian troop kill clash monitor',
 'syria regim bomb kill includ children',
 'twin blast kill kurdish fighter syria monitor',
 'us led strike syria kill jihadist overnight monitor',
 'us led raid syria kill jihadist civilian',
 'us strike kill qaeda fighter syria monitor',
 'us led strike hit qaeda syria well monitor',
 'us led strike syria kill jihadist monitor',
 'syria air strike kill includ children monitor',
 'jihadist kill fight syria kurd monitor',
 'syria air strike kill dozen rebel town monitor',
 'worker dig dead syria regim strike aleppo',
 'updat regim air raid kill near syria capit new toll',
 'american among jihadist kill syria raid ngo',
 'syria armi kill rebel daraa provinc ambush ngo',
 'syria bomb jihadist posit raqa second day',
 'kill syria daraa aleppo ngo',
 'air raid kill jihadist syria raqa ngo',
 'syria troop kill least jihadist near lebanon monitor',
 'syria air strike jihadist camp kill new toll',
 'syria troop kill jihadist advanc monitor',
 'syria air raid kill islam state milit monitor',
 'russian strike kill civilian syria deir ezzor monitor',
 'car bomb kill eastern syria state media',
 'least kill air strike syrian market town observatori',
 'air raid kill civilian north syria town monitor',
 'bodi civilian found syrian town taken group',
 'rebel shell kill four civilian damascu monitor',
 'least dead syria market air strike monitor',
 'russia strike kill group fighter foreign mercenari syria',
 'monitor kill missil strike eastern syria citi',
 'us led strike kill civilian syria raqa monitor',
 'least kill north syria aleppo monitor',
 'russia regim strike kill east syria monitor',
 'civilian kill raid syria group bastion raqa monitor',
 'syria rebel kill aleppo assault captur villag monitor',
 'air strike syria idlib kill monitor',
 'civilian dead air strike market east syria monitor',
 'syria regim raid aleppo kill civilian monitor',
 'updat syria regim strike near aleppo civil defenc',
 'suicid bomber kill one syria regim stronghold state tv',
 'children among dead syria regim bomb civil defenc',
 'opposit minist among dead syria car bomb rebel',
 'civilian kill syria aid convoy attack red cross',
 'russia say syrian troop kill us led strike',
 'kill raid syria idlib monitor',
 'new strike kill least civilian syria aleppo monitor',
 'syrian armi say rebel bombard aleppo kill three day',
 'dozen civilian dead rebel assault aleppo',
 'rebel aleppo attack putin cautiou new russian raid',
 'rebel fire kill aleppo schoolchildren state media',
 'syria monitor say air strike kill school rebel held idlib',
 'group group land mine kill wound dozen syrian town',
 'dead heavi bombard syria idlib monitor',
 'air raid kill least civilian syria aleppo monitor',
 'turkish militari say group milit kill northern syria',
 'blast syria turkey border kill rebel monitor',
 'suicid attack syria wed kill medic sourc',
 'isil crucifi men syria aleppo ngo',
 'least syrian soldier kill isra raid ngo',
 'jihadist execut three syria rebel offic monitor',
 'car bomb kill least syria hama state media region world ahram onlin',
 'syria air raid displac person camp kill ngo region world ahram onlin',
 'dead syria barrel bomb attack aleppo',
 'syria rebel infight kill fighter day region world ahram onlin',
 'car bomb syria hom kill governor region world ahram onlin',
 'kill syria rebel shell assad elect ralli monitor region world ahram onlin',
 'syrian armi missil kill includ kid region world ahram onlin',
 'bomb syria idlib kill govern fighter monitor group region world ahram onlin',
 'children among dead syria car bomb state media region world ahram onlin',
 'car bomb rocket fire kill syria hom governor region world ahram onlin',
 'mortar fire damascu kill wound state media region world ahram onlin',
 'dead rebel fire regim part aleppo ngo region world ahram onlin',
 'dead two day clash syria daraa monitor region world ahram onlin',
 'air raid kill syria market monitor region world ahram onlin',
 'air strike kill dozen syria aleppo monitor group region world ahram onlin',
 'twin car bomb kill syria hom state media region world ahram onlin',
 'rebel dead syria prematur car bomb blast ngo region world ahram onlin',
 'mortar fire kill two damascu opera hous state media region world ahram onlin',
 'syria rebel jihadist kill ngo region world ahram onlin',
 'car bomb kill six syria hom ngo region world ahram onlin',
 'car bomb blast kill syria hom ngo region world ahram onlin',
 'five dead blast secur hq central syria ngo region world ahram onlin',
 'isra attack syria militari camp kill three jordan time',
 'dozen dead car bomb hit syria evacue jordan time',
 'strike kill near syria daesh held raqqa monitor jordan time',
 'outrag syria chemic attack kill dozen rebel held town jordan time',
 'five dead russian militari helicopt down syria jordan time',
 'dozen dead warplan pound rebel held north syria jordan time',
 'dozen dead warplan pound rebel held north syria jordan time',
 'least kill north syria aleppo monitor jordan time',
 'massiv daesh bomb attack kill syrian kurdish citi jordan time',
 'syria regim advanc rebel aleppo monitor jordan time',
 'civilian kill regim air raid northern syria jordan time',
 'barrel bomb kill civilian daesh town syria jordan time',
 'syria regim air strike kill least monitor jordan time',
 'syria air strike kill least monitor jordan time',
 'syria regim air strike kill near damascu monitor jordan time',
 'massiv daesh bomb attack kill syrian kurdish citi jordan time',
 'least kill north syria aleppo monitor jordan time',
 'syria rebel kill aleppo assault captur villag monitor jordan time',
 'raid syria market kill hundr flee daesh bastion jordan time',
 'dead daesh counterattack syria regim forc jordan time',
 'syrian russian aircraft step bomb aleppo citi monitor jordan time',
 'syria air strike kill mostli children outsid school jordan time',
 'syrian govern push damascu rebel enclav kill least jordan time',
 'air strike kill syria truce zone monitor jordan time',
 'syria regim bombard kill schoolchildren besieg enclav jordan time',
 'russian strike kill flee civilian east syria monitor jordan time',
 'us led strike kill civilian syria raqqa monitor jordan time',
 'russia say kill extremist mercenari syria claim shishani death jordan time',
 'nation news agenc damascu explos due rocket bomb',
 'nation news agenc blast syria hom kill children',
 'nation news agenc coalit raid kill isil fighter',
 'least kill bomb hit bu convoy syria',
 'us led air strike syria kill dozen civilian',
 'two russian pilot kill syria daesh down chopper',
 'us jet kill least civilian syria',
 'russian strike kill aleppo',
 'syrian russian air strike kill civilian idlib',
 'syrian russian air strike kill citi ashara',
 'suicid attack near shia shrine kill syrian observatori',
 'russian syrian strike kill civilian',
 'us russia broker syria truce end',
 'air strike syria kill least peopl',
 'string bomb blast kill least syria',
 'heavi air strike hit opposit held part aleppo',
 'unicef say schoolchildren six teacher kill syria raid',
 'russian syrian regim strike kill aleppo',
 'car bomb syria kill least near turkish border',
 'russian jet resum airstrik aleppo',
 'suicid bomb kill syria turkey border',
 'suicid bomber target syrian wed kill',
 'car bomb attack kill least syria war monitor say',
 'air strike kill dozen insid syria de escal zone',
 'least seven children die regim shell rebel held area syria',
 'least civilian kill russian regim air strike syria',
 'russia air strike kill least civilian syria monitor',
 'least dead suicid bomb hit damascu',
 'unidentifi air strike kill least eight hezbollah fighter syria',
 'least kill dozen injur twin bomb target syria qamishli near turkish border daili sabah',
 'air strike syrian hospit kill monitor group say daili sabah',
 'civilian kill russian air strike syria aleppo daili sabah',
 'russian airstrik target civilian syria idlib kill daili sabah',
 'daesh russia syrian regim target opposit daili sabah',
 'syrian warplan pound idlib leav dead daili sabah',
 'assad regim helicopt kill peopl barrel bomb aleppo daili sabah',
 'syria use chemic weapon turkey offer remedi lnur evik daili sabah',
 'least civilian dead toxic ga attack syria idlib',
 'russian airstrik hit syrian opposit forc',
 'opposit forc claim fighter kill other injur russian airstrik syria idlib',
 'russian strike kill civilian syria idlib monitor',
 'bomb kill woman wound syria hom',
 'daesh terrorist kill men syria deir el zour daili sabah',
 'us coalit airstrik kill civilian east syria',
 'airstrik northern eastern syria kill civilian activist',
 'least dead blast target evacu convoy strand near aleppo',
 'us led coalit airstrik kill partner forc pentagon say',
 'civilian kill injur assad regim airstrik syria idlib',
 'assad regim target civilian hom airstrik',
 'least white helmet rescuer kill airstrik syria hama',
 'airstrik assad regim warplan kill syria idlib destroy mosqu hama',
 'assad regim kill least refuge camp',
 'isi recaptur syrian ga field kill monitor group say',
 'least die barrel bomb attack syrian regim warplan',
 'kurdish fighter kill twin blast syria',
 'us led raid kill isi milit overnight monitor say',
 'school bomb kill children syria monitor',
 'terrorist kill n syria turkish artilleri coalit jet pound daesh target daili sabah',
 'regim russia air strike kill idlib strike continu pound road death aleppo',
 'daesh claim respons bomb near damascu least dead',
 'least kill dozen injur twin bomb target syria qamishli near turkish border',
 'coalit airstrik kill civilian daesh held villag syria manbij',
 'civilian kill syria hasakeh motorbik bomber attack',
 'assad regim airstrik kill civilian syria aleppo',
 'children kill airstrik eastern syria latest round russian syrian bomb unicef',
 'kill injur airstrik area near hospit marketplac syria aleppo',
 'civilian kill russian airstrik syria',
 'syrian regim bomb kill civilian aleppo region',
 'turkish militari kill daesh terrorist syria',
 'children teacher kill russian syrian airstrik near school idlib',
 'daesh mine kill wound dozen ypg held manbij hrw say',
 'aleppo airstrik kill peopl opposit held area',
 'kill injur russian air strike syria idlib',

In [30]:
onehot_rep=[one_hot(words,voc_size) for words in corpus]
onehot_rep[1]

[2090, 504, 3843, 2007, 3260, 3665, 862, 3835, 353, 4589, 1626, 2540]

# Embedding Represtation

In [32]:
sent_length=20
embedded_docs=pad_sequences(onehot_rep,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4907 2345 1815]
 [   0    0    0 ... 4589 1626 2540]
 [   0    0    0 ...    4 3260 3256]
 ...
 [   0    0    0 ... 2124 2651 4802]
 [   0    0    0 ... 1040  473 4779]
 [   0    0    0 ... 2599 1800 4472]]

In [38]:
embedding_vector_features = 40

model = Sequential()

model.add(Embedding(input_dim=voc_size,
                    output_dim=embedding_vector_features,
                    input_shape=(sent_length,)))

model.add(LSTM(100))
model.add(Dense(1, activation="sigmoid"))

model.compile(loss="binary_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
len(embedded_docs), Y.shape

(804, (804,))

In [42]:
import numpy as np

In [43]:
X_final=np.array(embedded_docs)
Y_final=np.array(Y)

In [44]:
X_final.shape,Y_final.shape

((804, 20), (804,))

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train,X_test,Y_train,Y_test=train_test_split(X_final,Y_final,test_size=0.33,random_state=42)

In [47]:
model.fit(X_train,Y_train,validation_data=(X_test,Y_test),epochs=10,batch_size=64)

Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.5294 - loss: 0.6930 - val_accuracy: 0.5564 - val_loss: 0.6900
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5291 - loss: 0.6900 - val_accuracy: 0.5564 - val_loss: 0.6905
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5358 - loss: 0.6885 - val_accuracy: 0.4962 - val_loss: 0.6932
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6645 - loss: 0.6801 - val_accuracy: 0.5301 - val_loss: 0.6942
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6865 - loss: 0.6608 - val_accuracy: 0.5414 - val_loss: 0.7359
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6856 - loss: 0.6124 - val_accuracy: 0.4699 - val_loss: 0.7206
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7093 - loss: 0.5928 - val_accuracy: 0.4624 - val_loss: 0.7368
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7577 - loss: 0.5648 - val_accuracy: 0.4850 - val_loss: 0.7472
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8082 - loss: 0.5010 - val_accuracy: 0.4850 - val_loss: 0.8283
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7708 - loss: 0.4757 - val_accuracy: 0.4699 - val_loss: 1.0597

# Adding Dropout

In [48]:
from tensorflow.keras.layers import Dropout

In [49]:
#creating Model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(input_dim=voc_size,
                    output_dim=embedding_vector_features,
                    input_shape=(sent_length,)))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation="sigmoid"))
model.compile(loss="binary_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 20, 40)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

# Performance Metrics And Accuracy

In [50]:
y_pred=model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

In [52]:
y_pred=np.where(y_pred > 0.6, 1,0)

In [53]:
from sklearn.metrics import confusion_matrix

In [55]:
confusion_matrix(Y_test,y_pred)

array([[118,   0],
       [148,   0]])

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.44360902255639095

In [58]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.44      1.00      0.61       118
           1       0.00      0.00      0.00       148

    accuracy                           0.44       266
   macro avg       0.22      0.50      0.31       266
weighted avg       0.20      0.44      0.27       266

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))